-- Run this in Supabase Dashboard -> SQL Editor.
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  completed_exercises integer not null default 0,
  minutes integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.workout_schedule (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  scheduled_for date not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.user_profiles enable row level security;
alter table public.workout_logs enable row level security;
alter table public.workout_schedule enable row level security;
drop policy if exists "Users manage own profile" on public.user_profiles;
create policy "Users manage own profile" on public.user_profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own workouts" on public.workout_logs;
create policy "Users manage own workouts" on public.workout_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own schedule" on public.workout_schedule;
create policy "Users manage own schedule" on public.workout_schedule for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
